# Generated by Django 6.0.2 on 2026-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_ingredient_dish_image_dish_likes_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='removed_ingredients',
            field=models.TextField(blank=True),
        ),
    ]
