# Generated by Django 6.0.2 on 2026-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_ingredient_is_required_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('canceled', 'Скасований'), ('done', 'Виконаний')], default='new', max_length=20),
        ),
    ]
