# Generated by Django 6.0.2 on 2026-05-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_required',
        ),
    ]
